{% set name = "ansible-runner" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 1bb56f9061c3238d89ec8871bc842f5b8d0e868f892347e8455c98d5b6fa58a1
  - folder: src
    url: https://github.com/ansible/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 2ac4c236d021503b34c3986b0bb35f75a39ac91848ab786946e136dc73b1e938

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ansible-runner = ansible_runner.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pexpect >=4.5
    - psutil
    - python >=3.6
    - python-daemon
    - pyyaml
    - six

test:
  source_files:
    - src/test/unit
  requires:
    - pytest
    - pytest-cov
    - mock
    - pip
  imports:
    - ansible_runner
  commands:
    - python -m pip check
    - ansible-runner --version
    - ansible-runner --help
    - cd src/test/unit
    - pytest --cov ansible_runner -vv -k "not test_env_vars"  # [osx]
    - pytest --cov ansible_runner -vv  # [linux]

about:
  home: https://github.com/ansible/ansible-runner
  license: Apache-2.0
  license_family: Apache
  license_file: dist/LICENSE.md
  doc_url: https://ansible-runner.readthedocs.io
  doc_source_url: https://github.com/ansible/ansible-runner/tree/master/docs
  summary: |
    A tool and python library that helps when interfacing with Ansible directly
    or as part of another system whether that be through a container image
    interface, as a standalone tool, or as a Python module that can be
    imported. The goal is to provide a stable and consistent interface
    abstraction to Ansible.

extra:
  recipe-maintainers:
    - bollwyvl
