{% set name = "ansible-runner" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: da6e5d0fe8060cbe4b9d8ed06c362219dbb8198bb40b8f56536f46658d9b9c1a
  - folder: src
    url: https://github.com/ansible/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 108beb606bcca6fa90882e832075f7a74b9ccf8c2ab1eac73a33d1f2b52a5a87

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ansible-runner = ansible_runner.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
    - pbr
  run:
    - pexpect >=4.5
    - psutil
    - python >=3.6
    - python-daemon
    - pyyaml
    - six

{% set skips = [
  "containerization",
  "env_vars",
  "prepare_env_sshkey",
  "container_volmount",
  "registry_auth_cleanup",
  "prepare_env_directory_isolation_from_settings",
] %}

test:
  source_files:
    - src/test/unit
  requires:
    # from /test/requirements.txt
    - ansible >=5.4.0,<5.5.0
    # TODO: unpin after https://github.com/conda-forge/ansible-feedstock/pull/93
    - ansible-core >=2.12.2,<2.13.0
    - pip
    - pytest
    - pytest-cov
    - pytest-timeout
    - pytest-mock
  imports:
    - ansible_runner
  commands:
    - python -m pip check
    - ansible-runner --version
    - ansible-runner --help
    - cd src/test/unit
    - pytest --cov ansible_runner -vv -k "not ({{ ' or '.join(skips) }})" --cov-report term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/ansible/ansible-runner
  license: Apache-2.0
  license_family: Apache
  license_file: dist/LICENSE.md
  doc_url: https://ansible-runner.readthedocs.io
  doc_source_url: https://github.com/ansible/ansible-runner/tree/master/docs
  summary: |
    A tool and python library that helps when interfacing with Ansible directly
    or as part of another system whether that be through a container image
    interface, as a standalone tool, or as a Python module that can be
    imported. The goal is to provide a stable and consistent interface
    abstraction to Ansible.

extra:
  recipe-maintainers:
    - bollwyvl
