travis:
  secure:
    BINSTAR_TOKEN: LMn0r9VshuZWcAk/HB8J3Ndf/+P6eTpZWCZhVM1JOaONnynS/TFSUCwGZQmANt+HLFPFhZviwUcGoaPF1ztw0/AYCgco+/XlXDlVZ0YkU8A7pxDaD1tHU00zDDzNkmsENwSxMRcfr28i39gBjjZl61I2HcqcK+DFKsIKndNMvPFUdDPvJNmKqncTs7FMb2AhbFdBXgvTTxsqT7HyOAe5VvSAwRED/Tt6S+cVBoMXhzZjBxlz8RkbuyMNKPyuYFrL50T8yFN84bSKrkRK6p+jHoo94mHWfGdLpT49PDQiCNCxu6VDW50CaqCqv5iYnGbpGYv4t9HcmTOp+ZzpDMtZ3Ljk2qYTVp5RcWtnTWW/l2CSf4ZMjsYVa2FXkZ06arXnmGQNFYxvKpxZ0j8CXv1oUOZ1b3m9OpZXzD1okPLCLKDbOxbyrtULS6H1J9qW4I3QMFngFh+NXkZBN0L9W+6dQ3S12TMSbaSz8fd8b0JEHd277XXMRCigjIMs3gVkAt1nHycaow9XhGsjxrf5PdG9acbQ/GdzfIYyq32LZC7vZl84dM4KhrljAzipybEeSMf2+Ni1FIwjy8IR09f8EgBQpTwF1XgFHWwLUmdKqpIv5Vkyrt/U7lak/PgPOJSC0QtVdnw9iATSqNCWKvP694g4D+7B+NsatG+DGYv2uARYfEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
